// AUTO-GENERATED by scripts/gen-version.ts. Do not edit by hand.
// Source of truth: `omnigraph.serverVersion` in the repo-root package.json.

/**
 * The omnigraph-server release this build of the SDK was generated against.
 * The SDK targets the corresponding OpenAPI spec exactly; behaviour against
 * a different server major.minor is undefined.
 */
export const SERVER_VERSION = "0.3.0";
