// AUTO-GENERATED by scripts/gen-version.ts. Do not edit by hand.
// Source of truth: `omnigraph.serverVersion` in the repo-root package.json.

/**
 * The omnigraph-server release this build of the SDK was generated against.
 * Requests require the corresponding major.minor HTTP contract; mismatched
 * discovery or response headers fail closed.
 */
export const SERVER_VERSION = "0.13.0";
export const HTTP_API_CONTRACT = "0.13";
export const HTTP_API_CONTRACT_HEADER = 'Omnigraph-Http-Api';
