// AUTO-GENERATED by scripts/gen-version.ts. Do not edit by hand.
// Source of truth: `version` in packages/mcp/package.json.

/**
 * The MCP server package version reported in the MCP initialize response.
 */
export const MCP_PACKAGE_VERSION = "0.8.0";
