import { readFileSync, writeFileSync } from 'node:fs';
import { join, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';

const ROOT = dirname(dirname(fileURLToPath(import.meta.url)));
const ROOT_PKG = join(ROOT, 'package.json');
const SDK_OUT = join(ROOT, 'packages/sdk/src/version.gen.ts');
const MCP_PKG = join(ROOT, 'packages/mcp/package.json');
const MCP_OUT = join(ROOT, 'packages/mcp/src/version.gen.ts');

const pkg = JSON.parse(readFileSync(ROOT_PKG, 'utf8')) as {
  omnigraph?: { serverVersion?: string };
};
const mcpPkg = JSON.parse(readFileSync(MCP_PKG, 'utf8')) as {
  version?: string;
};

const serverVersion = pkg.omnigraph?.serverVersion;
if (!serverVersion) {
  throw new Error(`omnigraph.serverVersion missing from ${ROOT_PKG}`);
}

const sdkBody = `// AUTO-GENERATED by scripts/gen-version.ts. Do not edit by hand.
// Source of truth: \`omnigraph.serverVersion\` in the repo-root package.json.

/**
 * The omnigraph-server release this build of the SDK was generated against.
 * The SDK targets the corresponding OpenAPI spec exactly; behaviour against
 * a different server major.minor is undefined.
 */
export const SERVER_VERSION = ${JSON.stringify(serverVersion)};
`;

const mcpVersion = mcpPkg.version;
if (!mcpVersion) {
  throw new Error(`version missing from ${MCP_PKG}`);
}

const mcpBody = `// AUTO-GENERATED by scripts/gen-version.ts. Do not edit by hand.
// Source of truth: \`version\` in packages/mcp/package.json.

/**
 * The MCP server package version reported in the MCP initialize response.
 */
export const MCP_PACKAGE_VERSION = ${JSON.stringify(mcpVersion)};
`;

writeFileSync(SDK_OUT, sdkBody);
writeFileSync(MCP_OUT, mcpBody);
console.log(`wrote ${SDK_OUT} (SERVER_VERSION=${serverVersion})`);
console.log(`wrote ${MCP_OUT} (MCP_PACKAGE_VERSION=${mcpVersion})`);
