import { readFileSync, writeFileSync } from 'node:fs';
import { join, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';

const ROOT = dirname(dirname(fileURLToPath(import.meta.url)));
const ROOT_PKG = join(ROOT, 'package.json');
const OUT = join(ROOT, 'packages/sdk/src/version.gen.ts');

const pkg = JSON.parse(readFileSync(ROOT_PKG, 'utf8')) as {
  omnigraph?: { serverVersion?: string };
};

const serverVersion = pkg.omnigraph?.serverVersion;
if (!serverVersion) {
  throw new Error(`omnigraph.serverVersion missing from ${ROOT_PKG}`);
}

const body = `// AUTO-GENERATED by scripts/gen-version.ts. Do not edit by hand.
// Source of truth: \`omnigraph.serverVersion\` in the repo-root package.json.

/**
 * The omnigraph-server release this build of the SDK was generated against.
 * The SDK targets the corresponding OpenAPI spec exactly; behaviour against
 * a different server major.minor is undefined.
 */
export const SERVER_VERSION = ${JSON.stringify(serverVersion)};
`;

writeFileSync(OUT, body);
console.log(`wrote ${OUT} (SERVER_VERSION=${serverVersion})`);
